name: React Native CI/CD on ubuntu-latest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]
        # or like this -> node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js, set up JDK 1.8
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        java-version: 1.8

    - name: react-native install
      run: |
        npm install -g react-native-cli
        export PATH=$PATH:$ANDROID_HOME/platform-tools

    - name: npm token
      run: |
        touch ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/.npmrc
      env:
        NPM_PUBLISH_TOKEN: ${{ secrets.NPM_TOKEN_FOR_GITHUB_ACTION }}

    - name: pack and prepare example
      run: |
        npm install
        ./prepare_example.sh

    - name: build example android
      run: |
        cd example/android
        ./gradlew assembleDebug

    - name: publish
      run: npm publish ./
      if: contains(github.ref, 'tags/v')
